### ISSUE TITLE
Grafana Dashboard Source

### ISSUE THREAD

**Issue by pfruh** [MI-OSiRIS/mi-osiris.github.io#3]
Sorry for using a GitHub issue to contact you, but I've found no official way to do so.

I saw the [post](http://www.osris.org/article/2017/12/07/the-influxdb-ceph-mgr-plugin) by @mhdo2 about the influxdb ceph-mgr plugin and was wondering if you would mind publishing the Grafana dashboard you created for the plugin on https://grafana.com/dashboards or somewhere in a repo.

**Comment by mhdo2** [comment]
Hello,
Here is the link to the published [dashboard](https://grafana.com/dashboards/4244).
Please note that this dashboard uses a different version of the ceph-mgr plugin than what's is on the master branch of Ceph. I will include both versions below. The main difference is that the version being used still uses the config file and has a pg_summary function which will be added to the master version later on. 
- [master version](https://github.com/ceph/ceph/tree/master/src/pybind/mgr/influx)
- [dashboard version](https://github.com/MI-OSiRIS/ceph/tree/influx_mod/src/pybind/mgr/influx)

**Comment by pfruh** [comment]
Awesome, thanks! :)
